### PR TITLE
Ensure vehicle requested pickup times come after return

### PR DESCRIPTION
**Pull request by ziruihao**
https://gyazo.com/6df1cfeaa77e255c9aa15a2f05487b81

#78 and #59

### CODE REVIEW

**Review by alexpetros — CHANGES_REQUESTED** [review]
Good stuff, but I'm not wild about the huge button for the error. Can have it just re-use the existing error message for a `400`? That'll scroll you back to the top of the screen, which is annoying, but then it's in a single place with the existing error messages, that into a little toast soon if we want.

**Comment by ziruihao** [comment]
> Good stuff, but I'm not wild about the huge button for the error. Can you have it just re-use the existing error message for a `400`? That'll scroll you back to the top of the screen, which is annoying, but then it's in a single place with the existing error messages, that we can turn into a little toast soon if we want.

I may be missing something, but should I just use `BadRequestError`? So now I'm just `throw new BadRequestError('Pickup time must be before return time')` in the `putVehicleRequest` function, but when I'm testing, it's not scrolling up to the top of the page, or displaying any error message on the frontend.

**Comment by alexpetros** [comment]
> but when I'm testing, it's not scrolling up to the top of the page, or displaying any error message on the frontend.

Nope, you're not missing anything—the config file that makes this happen isn't being imported because the script tag before it was syntactically incorrect. Whoops. 

https://github.com/dartmouth-outing-club/doc-trailhead/commit/51ca1fd3817bdb2deb563b48b3c21484b2f77fd5

With this change rebased before your commit, it works great! Awesome work. I'll make an issue to make that error message prettier too.

**Review by alexpetros — APPROVED** [review]

**Comment by alexpetros** [comment]
If you're curious what the config does: https://github.com/dartmouth-outing-club/doc-trailhead/blob/cea21da98930f2fdba96c3a3a0944979621d9b51/static/js/htmx-config.js

**Pull request merged**
